### ISSUE TITLE
Use new API version for OpenLibertyApplication

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/draft-guide-operators-openshift#102]
A new version of Open Liberty Operator was released recently. The APIs have breaking changes, hence the API version has been updated from `openliberty.io/v1beta1` to `apps.openliberty.io/v1beta2`. Update the guide to use the new API version. New version of the operator doesn't process the old API version `openliberty.io/v1beta1`.

notify @gkwan-ibm

**Comment by gkwan-ibm** [comment]
close
- the guide was updated

**Comment by leochr** [comment]
@gkwan-ibm Thanks for updating the guide. There are still some some references to the old API group and version:

- [x] In the following content, it should be `openlibertyapplications.apps.openliberty.io` instead of `openlibertyapplication.openliberty.io`

```
Look for the following output:

openlibertyapplication.openliberty.io/system configured
openlibertyapplication.openliberty.io/inventory unchanged
```

- [x] In the output below `This example shows part of the olapps/system output:`, it should be `apps.openliberty.io/v1beta2` instead of `openliberty.io/v1beta1`

**Comment by gkwan-ibm** [comment]
close
- the guide was updated
