### ISSUE TITLE
Update link to OpenShift web console

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/draft-guide-operators-openshift#125]
Link to OpenShift web console is pointing to an older unsupported version: 
https://docs.openshift.com/container-platform/4.5/web_console/web-console.html

_When you obtained your OpenShift cluster, you received login information for the [OpenShift web console](https://docs.openshift.com/container-platform/4.5/web_console/web-console.html). The web console provides an interface to interact with your OpenShift cluster through your web browser._

- [x] Update it to the latest:
https://docs.openshift.com/container-platform/latest/web_console/web-console.html

- [ ] Other guides may also have similar instances. Please update accordingly.

fyi @gkwan-ibm

**Comment by gkwan-ibm** [comment]
close
- updated this guide and the openliberty-operator-openshift guide
